cxf:
  jaxrs:
    #component-scan: true
    classes-scan: true
    classes-scan-packages: com.fasterxml.jackson.jaxrs, com.danny.rest

server:
  servlet:
    context-path: /cxf_rest_ws


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_crud
    username: nativeuser
    password: PmDbS@787
  security:
    user:
      name: danny
      password: danny
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect